baseURL = "https://akliuxingyuan.cc"
DefaultContentLanguage = "zh-hant" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "akliuxingyuan"
copyright = "akliuxingyuan. 本站遵循 CC-BY-NC 4.0 协议"
theme = "diary"
googleAnalytics = "G-3H1WESWSBQ" # TODO

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[markup.goldmark.renderer]
    unsafe = true

[params]
subtitle = "個人博客"
favicon = "https://avatars.githubusercontent.com/u/53224655"
# walineServer = "https://yourappaddress.vercel.app" # TODO
enableLaTeX=true
enableReadingTime=true
enableAutoDarkMode=true
# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "akliuxingyuan" # will set 'og:site_name'
description = "個人博客"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "歸檔"
weight = 1
[[menu.main]]
url = "/categories"
name = "分類"
weight = 2
[[menu.main]]
url = "/tags"
name = "標籤"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
